### ISSUE TITLE
[NOT AN ISSUE] I will be testing Osiris' detectability, for you all.

### ISSUE THREAD

**Issue by ryseDMT** [danielkrupinski/Osiris#1729]
I will do extensive testing on both ManualMap and LoadLibrary injection methods, different hooking methods, clean copies of the cheat and modified ones, using VacBypass, etc.

**Comment by xXTOO-HARDXx** [comment]
Thankyou. I am fairly sure that changing hooking methods to something involving .text patching (or minhook) should fix the detection issue, as I think the VMT Hooks must be the blame here, anything else in unruly..

;; Only game hooks can cause a bizarre situation like this; everyone getting overwatch bans, which turn to VAC. So sad :(

**Comment by VuBrian22** [comment]
> Thankyou. I am fairly sure that changing hooking methods to something involving .text patching (or minhook) should fix the detection issue, as I think the VMT Hooks must be the blame here, anything else in unruly..
> 
> ;; Only game hooks can cause a bizarre situation like this; everyone getting overwatch bans, which turn to VAC. So sad :(

haha the hint of sarcasm here. Anyhow even if it was the hooking methods in which I highly doubt it is, Daniel would be quick to change the hooking for us.

**Comment by xXTOO-HARDXx** [comment]
> > Thankyou. I am fairly sure that changing hooking methods to something involving .text patching (or minhook) should fix the detection issue, as I think the VMT Hooks must be the blame here, anything else in unruly..
> > ;; Only game hooks can cause a bizarre situation like this; everyone getting overwatch bans, which turn to VAC. So sad :(
> 
> haha the hint of sarcasm here. Anyhow even if it was the hooking methods in which I highly doubt it is, Daniel would be quick to change the hooking for us.

Agreed.

Also, just in terms of good measure, I think it's best that Daniel implements XOR strings, just, because.

From what I have in mind; If you think about it.. Osiris initialises some classes and pointers associated with the "Osiris" string, so when in memory, it's possible that VAC can detect this pointer in memory with that association.

Is a bit of wild idea but, I'm not sure. Correct me if I'm wrong.

**Comment by ryseDMT** [comment]
> haha the hint of sarcasm here. Anyhow even if it was the hooking methods in which I highly doubt it is, Daniel would be quick to change the hooking for us.

Yeah, when the hooking was crashing the client on join, Daniel changed it. He pointed out it was temporary, so I expect it to be changed soon. That doesn't really matter to me, my builds are going to use another hooking method. As for the testing, I will include the current one too.

**Comment by 0xE232FE** [comment]
Most of the bans is injector related. I am still not banned, no need for testing the cheat. Just test extensivly your injector ;-)

**Comment by Th3nd** [comment]
I just got OW banned, never even played a comp game, could be my injector tho.
![image](https://user-images.githubusercontent.com/45330378/84500511-fb64cf00-acb4-11ea-9ba6-6b4786388d51.png)

**Comment by adampala123** [comment]
Did you play wingman?

**Comment by Th3nd** [comment]
> Did you play wingman?

no.

**Comment by realstyla23** [comment]
still no ban either.. even tried the newest version without any modifications.. so yea..

**Comment by free0ne87** [comment]
> I just got OW banned, never even played a comp game, could be my injector tho.
> ![image](https://user-images.githubusercontent.com/45330378/84500511-fb64cf00-acb4-11ea-9ba6-6b4786388d51.png)

So maybe I was right..

**Comment by realstyla23** [comment]
what injector are u using

**Comment by VuBrian22** [comment]
I recommend just switching your injector over to Process Hacker 2 if that's the case. I haven't seen my accounts being banned as frequently if at all anymore when I switched over to it many months ago.

**Comment by xXTOO-HARDXx** [comment]
> I recommend just switching your injector over to Process Hacker 2 if that's the case. I haven't seen my accounts being banned as frequently if at all anymore when I switched over to it many months ago.

Yes, it may be because it uses a Kernel Driver to manage everything process related... Not everything, but some things, such as 'injecting'

**Comment by steel4me** [comment]
Really funny, 3 month later and see what happened :)

**Comment by aljawary** [comment]
> Really funny, 3 month later and see what happened, nobody believed me, even now, everyone deny it. Anyone who is interested should read these closed issues below.
> 
> It is really simple, stop using osiris till it get fixed.
> I wasted over 5 accounts with osisris and got vac, my osiris clone was highly modificated.
> I use my own injector over 15 years now, never got vac.
> 
> Im still using my injector over 3 month now. No vac, no ban, nothing. Just other dll, no osiris anymore ;)
> 
> #1246
> #1238
> #1251
> #1268
> #1306
did u mean osiris is has been detected right now?

**Comment by free0ne87** [comment]
I presume randoinjector is detected unless hooking isn't.

**Comment by MasterChief220** [comment]
guys use vac bypasser you wont get vac banned atleast.

**Comment by Jimmy-Baby** [comment]
> guys use vac bypasser you wont get vac banned atleast.
> 

That is not true

**Comment by MasterChief220** [comment]
> > guys use vac bypasser you wont get vac banned atleast.
> 
> That is not true

my friend has been using the free version of ezfrags with vac bypasser and he hasnt been banned yet. And its been a month.
