### ISSUE TITLE
Crashes game

### ISSUE THREAD

**Issue by Im-Beast** [danielkrupinski/Osiris#415]
After some time in game it crashes it with error:

 Engine Error
CutIrbtree overflow 

Thats very annoying, please fix :)

**Comment by danielkrupinski** [comment]
The issue occurs on official or community servers?

**Comment by Mufinekkk** [comment]
Community I think.

**Comment by l0ccy** [comment]
had it also once

**Comment by zazukq** [comment]
it happen at matchmaking too

**Comment by Shiv3RPolak** [comment]
It happen on both.

**Comment by wieisstimpee** [comment]
never happened to me

**Comment by kschou95** [comment]
the game will crash when i die

**Comment by wieisstimpee** [comment]
nvm just crashed XDDDDDDDDDDD

**Comment by wieisstimpee** [comment]
on official server

**Comment by wieisstimpee** [comment]
@danielkrupinski is this going to get fixed?! crashed after 2 rounds..

**Comment by danielkrupinski** [comment]
I cannot reproduce the issue. Could you please share your config?

**Comment by zazukq** [comment]
I think the problem is custom style menu, i make it window and dark and it not happen again

**Comment by wieisstimpee** [comment]
> I cannot reproduce the issue. Could you please share your config?

aimbot smoothness 20 fov 1.67 RCS 1.00 X and Y visible only, scoped, RCS based fov all checked. triggerbot enabled on key 0x4 scoped only and all hitgroup 10ms shot delay chams allies visible only blue enemies visible only pink glow projectejectlies (idk how to write that cant check rn) i got my own custom style misc all enabled other than ANTI AFK auto reload, auto accept hit sound gamesense

**Comment by wieisstimpee** [comment]
> I think the problem is custom style menu, i make it window and dark and it not happen again

will try that out, but i didnt get any error message it just crashes csgo and shows my desktop

**Comment by mdilai** [comment]
Can confirm random crashes after yesterday update. "CutIrbtree overflow" is related to a memory leak somewhere.
This can be caused by recent changes to GlowObjectManager, as well as by CSGO update and some signature changes. Unfortunately, as soon as i attach debugger, any сrashes magically disappearing.
Crashing going absolutely random - on map loading, after killing few enemies, after my death, after taking hostage by teammate, just during walking on map. Also it seems to me that crashes occur more often when playing on full server (like 20 players deathmatch) and not happen at all on casual with 6 real players and 4 bots.
Will update with call stack if get a luck.

**Comment by kschou95** [comment]
@danielkrupinski idk y.. here's my config... it crashes whenever i got killed
[1.zip](https://github.com/danielkrupinski/Osiris/files/3488439/1.zip)

**Comment by mdilai** [comment]
Finally catch a crash with debugger. Was during map change. It's definitely related to Glow function.
![OnMapChange](https://user-images.githubusercontent.com/6862357/62817776-a9a76180-bb44-11e9-838b-f7afb865926b.png)
![OnMapChangeCallStack](https://user-images.githubusercontent.com/6862357/62817777-aca25200-bb44-11e9-913d-be09c14f2c82.png)

Going try to catch a crash in other situations, maybe will get some more details.

**Comment by KyleIsDork** [comment]
> Finally catch a crash with debugger. Was during map change. It's definitely related to Glow function.
> ![OnMapChange](https://user-images.githubusercontent.com/6862357/62817776-a9a76180-bb44-11e9-838b-f7afb865926b.png)
> ![OnMapChangeCallStack](https://user-images.githubusercontent.com/6862357/62817777-aca25200-bb44-11e9-913d-be09c14f2c82.png)
> 
> Going try to catch a crash in other situations, maybe will get some more details.

Any solution going forward? I might use an older version if I can't get this one to work :p

**Comment by mdilai** [comment]
> Any solution going forward? I might use an older version if I can't get this one to work :p

The most quick & dirty "solution" - comment out line 
`Glow::render();`
 inside
`static int __stdcall doPostScreenEffects(int param) noexcept` 
function at _Hooks.cpp_. 

No Glow - no problem xD

For proper solution we need to wait until Daniel wake up, i am doubt anybody else understand what the hell is going in Glow.cpp

**Comment by danielkrupinski** [comment]
The problem related to custom glow entities. Temporary fix would be commenting out these lines https://github.com/danielkrupinski/Osiris/blob/45eeb846a93b9f4b2b0face67c41164b61c9d889/Osiris/Hacks/Glow.cpp#L29-L30

**Comment by wieisstimpee** [comment]
> The problem related to custom glow entities. Temporary fix would be commenting out these lines
> 
> https://github.com/danielkrupinski/Osiris/blob/45eeb846a93b9f4b2b0face67c41164b61c9d889/Osiris/Hacks/Glow.cpp#L29-L30

Thanks!

**Comment by danielkrupinski** [comment]
Glow crash should be fixed now!

**Comment by Shiv3RPolak** [comment]
But i wasn't using glow, and the game was crashing with this issue :o

**Comment by Grazyyt** [comment]
@danielkrupinski My Game keeps crashing every 2-5 Rounds it says engine error.

I removed Triggerbot,Glow,Reportbot and Antiaim (because I dont need that). but it does crash everytime.
Let me try some thing to know why its crashing

**Comment by wieisstimpee** [comment]
> @danielkrupinski My Game keeps crashing every 2-5 Rounds it says engine error.
> 
> I removed Triggerbot,Glow,Reportbot and Antiaim (because I dont need that). but it does crash everytime.
> Let me try some thing to know why its crashing

Make sure to remove those features from the hook too, also try not using a custom style that may be the cause. Although I do not crash since Daniel fixed the glow..

**Comment by sambrashaw** [comment]
Unfortunately, the crash is still prominent in my game, however this is strange as it doesn't happen to my friends who also use the cheat. I have no clue as to what may be the cause.

**Comment by CoolAsRice** [comment]
It still crashes with the cutlrbtree overflow message. I manual map with my injector and I've also VMprotected my dll as well. Idk what causes the crash, but I've tried attaching a debugger and it crashes less often. Please advise.

**Comment by Grazyyt** [comment]
> It still crashes with the cutlrbtree overflow message. I manual map with my injector and I've also VMprotected my dll as well. Idk what causes the crash, but I've tried attaching a debugger and it crashes less often. Please advise.

The menu style changer caused my crashes. since I left it by default, it didn't crash anymore.

**Comment by Vonr** [comment]
crashes for me

**Comment by ADGAYMILK** [comment]
Now crash for me

**Comment by ADGAYMILK** [comment]
I cant join a game...it crashes while loading

please,help me.

**Comment by xAkiraMiura** [comment]
the original post is from august 2019... can we make a new issue and not necro?

**Comment by ADGAYMILK** [comment]
Thankyou guys!
