### ISSUE TITLE
Aimbot Auto Shot deprecated?

### ISSUE THREAD

**Issue by steel4me** [danielkrupinski/Osiris#748]
If you turn on Auto Shot with following Aimbot Settings:
Aimbot Enabled: On
Aimkey Hold: Mouse 5
Aimlock: **Off**
Auto Shot: On
FOV: 75
Smooth: 20

Aimbot shoots directly while moving to target bone / hitbox. That's really annoying and i think, not normal. 

Aimbot should first lock to target bone / hitbox and then shoot.

Can someone doublecheck this please? 
What do you think?

**Comment by thomas0aotian** [comment]
Aimlock should never be enabled if u don't know how it works

**Comment by thomas0aotian** [comment]
Just try disable aimlock

**Comment by steel4me** [comment]
> Aimlock should never be enabled if u don't know how it works
Okay, Aimlock holds crosshair on enemy without using hold when switching to toggle mode.

> Just try disable aimlock
Okay, done!
Still the same... Aimbot directly shoots when Auto Shot is enabled. I mean, normally the aimbot should start shooting when crosshair is on target bone / hitbox, not before.
Can somone confirm? Or is this normal?

**Comment by notgoodusename** [comment]
its a bug enable triggerbot disable auto shot, toggle aimlock should work

**Comment by thomas0aotian** [comment]
agreed

**Comment by steel4me** [comment]
thx for information, i made this pull -> https://github.com/danielkrupinski/Osiris/pull/731 
works for me ;) i will have a look, also for standalone RCS or has someone already done this?
I think aimbot is not really legit when you spray cause shots go up after enemy is down...

**Comment by thomas0aotian** [comment]
@steel4me its not working on my end

**Comment by thomas0aotian** [comment]
@steel4me standalone rcs is almost the same difficulties as building an aimbot. It's pretty hard to implement

**Comment by thomas0aotian** [comment]
Prob jusy gonna wait till daddy Daniel figure it out

**Comment by steel4me** [comment]
> @steel4me its not working on my end

try it with mouse 1 hold not toggle and activate aimlock. on trigger just use mouse5 or alt with activated triggeraim. it works ;)

**Comment by thomas0aotian** [comment]
Alright still why don't u just make a keybind to toggle aimlock it works just the same way but easier and will not effect my normal aimbot

**Comment by thomas0aotian** [comment]
@steel4me

**Comment by thomas0aotian** [comment]
I can do a pr 4 better triggeraim

**Comment by steel4me** [comment]
> I can do a pr 4 better triggeraim

you are welcome ;) would be nice to see the way you would solve it...
thats why i asked, but this has nothing to do with this issue.

**Comment by thomas0aotian** [comment]
@steel4me ikr lmao

**Comment by thomas0aotian** [comment]
Alright bud I still don't know why are u tryna autoshoot with a high ass fov

**Comment by thomas0aotian** [comment]
done ima post the pr later

**Comment by thomas0aotian** [comment]
Fix for aimbot auto shoot/ Trigger Aim(Magnet Triggerbot) here #751

**Comment by steel4me** [comment]
> Alright bud I still don't know why are u tryna autoshoot with a high ass fov

lmao, this high fov was just for the issue that you see wqhat i mean. i don't play like this ^^

**Comment by xAkiraMiura** [comment]
is your problem solved? if so please close the issue

also the solution @thomas0aotian said is terrible,
disable aimlock, what it does is lock on even when not shooting
make sure your min damage and chance is not the problem
recoil scale X and Y need to be at 100%
auto shot does indeed work, there is no need for using the triggerbot.

oh and the triggerbot doesnt shoot though wall so no autowall if you do decide to follow his terrible advice.

also can you stop bullshitting about an RCS being hard to make? you literally just store the previous angle, do some math on the punch netvar and then add it.

**Comment by steel4me** [comment]
No the problem was not solved. I was playing RDR2 long time, never tried csgo again. I already did standalone RCS and made a pull request and yes it was not really hard to make. 

As i wrote it, i was able to understand that you have to lower the "max angle delta" under misc to make autoshoot working correctly...Thats the solution

most of users here are writing trash and think their solutions are absolutly correct ;) i stopped to say or write anything cause, it's useless....but here you go i close 1 of 99999 open issues, most of them are no issues
