### ISSUE TITLE
:D

### ISSUE THREAD

**Issue by agshaidun** [danielkrupinski/Osiris#906]
https://youtu.be/4IZai_BSBNM

**Comment by tirziz** [comment]
never try osiris in hvh server tho, how can it hit without resolver haha

**Comment by SmakHvh** [comment]
Mate I've gone 10-28 with Osiris vsing ot and gamesneeze seems like a cfg
problem hehe

**Comment by VeLocityYT** [comment]
that anti-aim tho

**Comment by Chopard** [comment]
cfg?

**Comment by AbdallahMehiz** [comment]
> https://youtu.be/4IZai_BSBNM

Can you upload the cfg?

**Comment by AbdallahMehiz** [comment]
> https://youtu.be/4IZai_BSBNM

bro 2:04 on the video
you were actually able to throw the smoke with AA
it doesn't work that way in the cheat man, grenades must be fixed with AA

**Comment by effex1337** [comment]
https://github.com/danielkrupinski/Osiris/pull/432
Antiaim with nades fix

**Comment by effex1337** [comment]
A lil outdated you should update urself

**Comment by agshaidun** [comment]
> > https://youtu.be/4IZai_BSBNM
> 
> bro 2:04 on the video
> you were actually able to throw the smoke with AA
> it doesn't work that way in the cheat man, grenades must be fixed with AA

I didn't fix the AA . Just double click when you throw the nade and it will throw perfectly.

**Comment by agshaidun** [comment]
> > https://youtu.be/4IZai_BSBNM
> 
> Can you upload the cfg?

Email

**Comment by VeLocityYT** [comment]
can you send me your config?
my discord 4ntifrag[Virtualxposed]#3838

**Comment by agshaidun** [comment]
> 
> 
> can you send me your config?
> my discord 4ntifrag[Virtualxposed]#3838

i don't have discord

**Comment by ifoverload** [comment]
Have you fixed the velocity slide?

**Comment by agshaidun** [comment]
> 
> 
> @agshaidun Have you fixed the velocity slide?

nope

**Comment by VeLocityYT** [comment]
> 
> 
> > can you send me your config?
> > my discord 4ntifrag[Virtualxposed]#3838
> 
> i don't have discord

My email? primeminishack@gmail.com

**Comment by agshaidun** [comment]
> 
> 
> > > can you send me your config?
> > > my discord 4ntifrag[Virtualxposed]#3838
> > 
> > 
> > i don't have discord
> 
> My email? [primeminishack@gmail.com](mailto:primeminishack@gmail.com)

Done

**Comment by num3rical** [comment]
Could I get the config as well @agshaidun ? damienisajew666@gmail.com

**Comment by agshaidun** [comment]
> 
> 
> Could I get the config as well @agshaidun ? [damienisajew666@gmail.com](mailto:damienisajew666@gmail.com)

check ur mail

**Comment by num3rical** [comment]
> 
> 
> > Could I get the config as well @agshaidun ? [damienisajew666@gmail.com](mailto:damienisajew666@gmail.com)
> 
> check ur mail

good stuff, thank you!

**Comment by agshaidun** [comment]
> 
> 
> > > Could I get the config as well @agshaidun ? [damienisajew666@gmail.com](mailto:damienisajew666@gmail.com)
> > 
> > 
> > check ur mail
> 
> good stuff, thank you!

Np

**Comment by AbdallahMehiz** [comment]
> > > > Could I get the config as well @agshaidun ? [damienisajew666@gmail.com](mailto:damienisajew666@gmail.com)
> > > 
> > > 
> > > check ur mail
> > 
> > 
> > good stuff, thank you!
> 
> Np

can i get it too? xd
abdallahmehiz0@gmail.com

**Comment by agshaidun** [comment]
> > > > > Could I get the config as well @agshaidun ? [damienisajew666@gmail.com](mailto:damienisajew666@gmail.com)
> > > > 
> > > > 
> > > > check ur mail
> > > 
> > > 
> > > good stuff, thank you!
> > 
> > 
> > Np
> 
> can i get it too? xd
> [abdallahmehiz0@gmail.com](mailto:abdallahmehiz0@gmail.com)

Check

**Comment by MaximovInk** [comment]
> 
> 
> > > > > > Could I get the config as well @agshaidun ? [damienisajew666@gmail.com](mailto:damienisajew666@gmail.com)
> > > > > 
> > > > > 
> > > > > check ur mail
> > > > 
> > > > 
> > > > good stuff, thank you!
> > > 
> > > 
> > > Np
> > 
> > 
> > can i get it too? xd
> > [abdallahmehiz0@gmail.com](mailto:abdallahmehiz0@gmail.com)
> 
> Check

ghostbusteraleha1@gmail.com
send me pls :0
